# Stock Portfolio Tracker
# CodeAlpha Internship - Python Programming Task 2

def get_stock_prices():
    # Hardcoded stock prices (as per simplified scope)
    return {
        "AAPL": 180,
        "TSLA": 250,
        "GOOGL": 140,
        "MSFT": 330,
        "AMZN": 175
    }

def get_user_inputs():
    """
    Ask the user for stock names and quantities.
    Returns a list of tuples: [(stock_name, quantity), ...]
    """
    holdings = []
    print("\n--- Stock Portfolio Tracker ---")
    print("Available stocks: AAPL, TSLA, GOOGL, MSFT, AMZN")
    print("Type 'done' as stock name when finished.\n")

    while True:
        stock = input("Enter stock name (or 'done' to finish): ").strip().upper()
        if stock == "DONE":
            break
        if stock not in get_stock_prices():
            print("Unknown stock. Please choose from available stocks.\n")
            continue

        try:
            qty = int(input(f"Enter quantity for {stock}: "))
            if qty < 0:
                print("Quantity cannot be negative.\n")
                continue
        except ValueError:
            print("Invalid quantity. Please enter a number.\n")
            continue

        holdings.append((stock, qty))
        print()

    return holdings

def calculate_portfolio(holdings, prices):
    """
    Calculate total investment and per-stock values.
    Returns:
      - details: list of dicts with stock, qty, price, value
      - total_value: total investment
    """
    details = []
    total_value = 0

    for stock, qty in holdings:
        price = prices[stock]
        value = price * qty
        details.append({
            "stock": stock,
            "quantity": qty,
            "price": price,
            "value": value
        })
        total_value += value

    return details, total_value

def save_report(details, total_value, filename="outputs/portfolio_report.txt"):
    """
    Save portfolio report to a text file.
    """
    with open(filename, "w") as f:
        f.write("=== Stock Portfolio Report ===\n\n")
        f.write(f"{'Stock':<10} {'Quantity':>10} {'Price ($)':>12} {'Value ($)':>12}\n")
        f.write("-" * 46 + "\n")

        for row in details:
            f.write(f"{row['stock']:<10} {row['quantity']:>10} "
                    f"{row['price']:>12.2f} {row['value']:>12.2f}\n")

        f.write("-" * 46 + "\n")
        f.write(f"{'Total Investment':<34} {total_value:>12.2f}\n")
        f.write("\nReport generated by CodeAlpha Internship Project.\n")

def display_report(details, total_value):
    """
    Display portfolio summary in the terminal.
    """
    print("\n=== Portfolio Summary ===")
    print(f"{'Stock':<10} {'Quantity':>10} {'Price ($)':>12} {'Value ($)':>12}")
    print("-" * 46)

    for row in details:
        print(f"{row['stock']:<10} {row['quantity']:>10} "
              f"{row['price']:>12.2f} {row['value']:>12.2f}")

    print("-" * 46)
    print(f"{'Total Investment':<34} ${total_value:>11.2f}")
    print()

def main():
    prices = get_stock_prices()
    holdings = get_user_inputs()

    if not holdings:
        print("No stocks entered. Exiting.")
        return

    details, total_value = calculate_portfolio(holdings, prices)
    display_report(details, total_value)

    save = input("Save report to outputs/portfolio_report.txt? (y/n): ").strip().lower()
    if save == "y":
        save_report(details, total_value)
        print("Report saved successfully.")

if __name__ == "__main__":
    main()